export default {
  user: {
    CHANGE_DESCRIPTION: 'user/CHANGE_DESCRIPTION',
    CHANGE_USERNAME: 'user/CHANGE_USERNAME',
    UPDATE_AVATAR: 'user/UPDATE_AVATAR',
    REMOVE_AVATAR: 'user/REMOVE_AVATAR',
    CHANGE_EMAIL: 'user/CHANGE_EMAIL',
    CHANGE_NAME: 'user/CHANGE_NAME',
    LOGOUT: 'user/LOGOUT',
    LOGIN: 'user/LOGIN'
  }
};
